name: Build VSIX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Restore packages using MSBuild
      - name: Restore packages with MSBuild
        run: msbuild TestcontainersDebugger.sln /t:Restore

      # Build the solution using MSBuild
      - name: Build solution
        run: msbuild TestcontainersDebugger.sln t:Build /p:Configuration=Release /

      # (Optional) Upload the generated VSIX as an artifact
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: src/TestcontainersDebugger/bin/Release/TestcontainersDebugger.vsix
